DATABASE


CREATE TABLE IF NOT EXISTS `simples` (
`id` int(11) NOT NULL,
  `titulo` varchar(255) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

ALTER TABLE `simples`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `simples`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=3;